services:
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    volumes:
      - ./data/influxdbv2:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=mainOrg
      - DOCKER_INFLUXDB_INIT_BUCKET=monitoring
    ports:
      - "8086:8086"
    networks:
      - monitoring_network
networks:
  monitoring_network:
    driver: bridge
